# Generated by Django 3.1 on 2020-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('company_url', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('company_logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
