# Generated by Django 3.1 on 2020-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
